name: Deploy to Google Play Internal Track

on:
  push:
    branches: [ dev ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - '.github/workflows/deployToGoogle.yml'
  workflow_dispatch:

jobs:
  build:
    name: Deploy to Google Play Internal Track
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: nttld/setup-ndk@v1.4.1
        with:
          ndk-version: r26b

      - name: Setup JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 20
          distribution: temurin

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            ${{ github.workspace }}/.ccache
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-

      - name: File Permissions
        run: chmod +x gradlew

      - name: Accept Preview SDK License
        run: echo -n -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > /usr/local/lib/android/sdk/licenses/android-sdk-preview-license

      - name: Build Bundle
        id: buildBundle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: wrapper
          arguments: bundleRelease

      - name: Sign artifact
        id: signArtifact
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: app/build/outputs/bundle/release
          keyAlias: ${{ secrets.KEYALIAS }}
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: '34.0.0'

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Artifact
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create whatsNew
        run: mkdir distribution/; echo '${{ github.event.head_commit.message }}' > distribution/whatsnew-en-US

      - name: Deploy to Internal Track
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.dertyp7214.rboardmanager
          releaseFiles: app/build/outputs/bundle/release/*.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          track: internal
          whatsNewDirectory: distribution/